# Generated by Django 5.0.3 on 2024-04-11 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybal', '0003_notification_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followerscount',
            name='user',
        ),
        migrations.AddField(
            model_name='followerscount',
            name='followed_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='zybal.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='followerscount',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='zybal.profile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zybal.profile'),
        ),
    ]
