# Generated by Django 5.0.3 on 2024-04-11 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybal', '0005_alter_followerscount_followed_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followerscount',
            name='followed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='zybal.profile'),
        ),
        migrations.AlterField(
            model_name='followerscount',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='zybal.profile'),
        ),
    ]
