# Generated by Django 5.0.3 on 2024-04-11 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybal', '0006_alter_followerscount_followed_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_liked', to='zybal.profile'),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to='zybal.profile'),
        ),
    ]
