# Generated by Django 5.0.4 on 2024-04-13 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybal', '0008_remove_profile_id_user_notification_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='no_of_likes',
        ),
        migrations.AddField(
            model_name='notification',
            name='target_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zybal.post'),
        ),
    ]
