# Generated by Django 5.0.3 on 2024-04-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zybal', '0009_rename_post_id_likepost_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('follow', 'Follow'), ('unfollow', 'Unfollow'), ('post', 'Post')], max_length=20, null=True),
        ),
    ]
